[package]
name = "cli_run"
version = "0.1.0"
edition = "2021"

[dependencies]
cli = {path="../cli"}
reqwest = {version="0.12.12", features=["blocking"]}
serde = "1.0.217"
serde_json = "1.0.133"
toml = "0.8.19"
